name: deepforestcast
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - affine=2.3.0
  - appdirs=1.4.4
  - argh=0.26.2
  - attrs=21.2.0
  - black=19.10b0
  - brotlipy=0.7.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - click=8.0.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - configparser=5.0.2
  - cryptography=3.4.7
  - cycler=0.10.0
  - docker-pycreds=0.4.0
  - fiona=1.8.13
  - flake8=3.9.2
  - fonttools=4.25.0
  - gdal=3.0.2
  - geopandas=0.6.1
  - gitdb=4.0.7
  - gitpython=3.1.18
  - gql=0.1.0
  - graphql-core=2.3.2
  - idna=2.10
  - importlib-metadata=4.6.1
  - joblib=1.0.1
  - kiwisolver=1.3.1
  - lz4=3.0.2
  - matplotlib=3.4.2
  - mccabe=0.6.1
  - mkl-fft=1.3.0
  - mkl-random=1.2.1
  - mkl-service=2.3.0
  - munch=2.5.0
  - munkres=1.1.4
  - mypy-extensions=0.4.3
  - numpy=1.21.0
  - nvidia-ml-py3=7.352.0
  - olefile=0.46
  - pandas=1.2.4
  - pathspec=0.8.1
  - pathtools=0.1.2
  - pillow=8.2.0
  - promise=2.3
  - protobuf=3.17.2
  - psutil=5.8.0
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pyflakes=2.3.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=2.4.2.post1
  - pysocks=1.7.1
  - python-dateutil=2.8.1
  - pytz=2021.1
  - pyyaml=6.0
  - rasterio=1.1.2
  - regex=2021.4.4
  - requests=2.25.1
  - rtree=0.9.7
  - scikit-learn=0.24.2
  - scikit-plot=0.3.7
  - scipy=1.6.3
  - sentry-sdk=1.1.0
  - shapely=1.7.0
  - shortuuid=1.0.1
  - six=1.16.0
  - smmap=4.0.0
  - snuggs=1.4.7
  - subprocess32=3.5.4
  - threadpoolctl=2.1.0
  - toml=0.10.2
  - torch=1.9.0
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tornado=6.1
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.0
  - urllib3=1.26.6
  - wandb=0.10.33
  - watchdog=2.1.3
  - zipp=3.5.0
